### PR TITLE
Fix #9 Unix timestamp not detected an throw an error

### LINKED ISSUE #9: Unix timestamp not detected and throw an error
When passing a unix timestamp, the formatter tries to format it as a string and throw an error:

`
Uncaught Exception: Failed to parse time string (1671062400) at position 8 (0): Unexpected character in (...)vendor/openpsa/ranger/src/Ranger.php:243
`

The issue is that prepare_date() first checks if the input is a string (although, technically, an integer is also a string).

I solved it by replacing

```
        if (is_string($input)) {
            return new Datetime($input);
        }
        if (is_int($input)) {
            $date = new Datetime;
            $date->setTimestamp($input);
            return $date;
        }
```
with
```
        if (is_numeric($input)) {
            $date = new Datetime;
            $date->setTimestamp($input);
            return $date;
        }
        if (is_string($input)) {
            return new Datetime($input);
        }
```

I also replaced is_int() by is_numeric(), which is the recommended way to distinguish a number from a string, is_int() failing in some cases.

### PR DESCRIPTION
**Pull request by magicoli**

### CODE REVIEW

**Comment by flack** [comment]
Thanks for the PR!

Can you add a small unittest that fails without your change and succeeds with it? Just to make sure there aren't any regressions in the future

File: src/Ranger.php [hunk 1]
```diff
@@ -234,14 +234,14 @@ private function prepare_date($input)
         if ($input instanceof DateTime) {
             return $input;
         }
-        if (is_string($input)) {
-            return new Datetime($input);
-        }
-        if (is_int($input)) {
+        if (is_numeric($input)) {
             $date = new Datetime;
             $date->setTimestamp($input);
```
Comment (flack) [inline src/Ranger.php]: according to https://www.php.net/manual/en/datetime.settimestamp.php, `setTimestamp` expects an int as the parameter, so maybe it would be good to cast here (because otherwise I guess you would at least get notices or somthing if this gets called with a float)

Comment (flack) [reply src/Ranger.php]: For example:

```php
declare(strict_types=1);
echo (new DateTime())->setTimestamp(1222222223.3222222);
```

Output:

```
Fatal error: Uncaught TypeError: DateTime::setTimestamp() expects parameter 1 to be int, float given in test.php:2 
Stack trace: 
#0 test.php(2): DateTime->setTimestamp() 
#1 {main} thrown in test.php on line 2
```

Comment (flack) [reply src/Ranger.php]: alternatively, we could say `if (is_numeric($input) && !is_float($input)) {` above

Comment (magicoli) [reply src/Ranger.php]: > alternatively, we could say `if (is_numeric($input) && !is_float($input)) {` above

I won't cast out floating numbers: although it might be rare (and useless) in this context, a timestamp can include microseconds, so instead of excluding them, I would rather use setTimestamp(intval($input)) to make sure an integer is passed, so it would meet any use case 

(actually I made tests it with floating numbers, and it worked fine, that's why I didn't include intval() in the fix, but this might be specific to my setup, I guess it's better to include it)

**Comment by magicoli** [comment]
I added a test unit, and pass intval($input) instead of $input to setTimestamp()

**Comment by flack** [comment]
Awesome, thanks!
